### PR TITLE
Merge master back to main

### PR DESCRIPTION
**Pull request by zeileis**
Mikis @mstasinopoulos, as discussed:

- I merged the GitHub `main` branch into your `master` branch containing the last CRAN release and resolved the conflict in the `DESCRIPTION` file.
- I think this is ready to be merged back to `main` now.
- Afterwards the `master` branch can be deleted.

### CODE REVIEW

**Comment by mstasinopoulos** [comment]
OK I think now I understand what is going on.  I was pushing things into `master` rather than `main`.

**Comment by mstasinopoulos** [comment]
Dear Achim

Thank you very much for your work. I would like to clarify in my mind what went wrong (not to be repeated)

My understanding is (please correct me if I am wrong) that there were two branches the original ‘master` and the ones you created `main’  to replace the ‘masters`

The old `master` was not deleted so when I was  pushing things there were going into ‘master` rather than ‘main’ and this created the problem

If I understand well what you have done say to gamlss.add is to put all things together into the `master`. 
Then push everything into `main` and then  delete the master 

Is that correct?


I will try (probably tomorrow) to go through your PR so we reserve the inconsistencies 

Thanks

Mikis

**Comment by zeileis** [comment]
I don't know how exactly the old `master` branches re-emerged. I'm fairly certain that when we moved everything to the new gamlss-dev organization I only renamed the existing master branches (if any) but did not create new ones.

The reason was to unify the name of the standard branch because GitHub had changed its default over the last years from master to main.

Possibly you kept the master label on your end and then created a new branch rather than rebasing after my renaming?

In any case: If we resolve all the main vs. master issues now, delete the old master branches, and make sure everyone pulls the most current GitHub version, we should be fine.

**Comment by zeileis** [comment]
Mikis, I just noticed that you only **closed** this PR but did not **merge** it!!

- I will check whether we can still re-apply your changes from the now deleted `master` branch.
- For all other PRs: Please make sure that you first **review** my changes, improve them if necessary, and then **merge** them!

**Comment by zeileis** [comment]
I re-applied the previous improvements directly in `main` now and applied a few further toch-ups. I hope I haven't overlooked anything.

**Comment by mstasinopoulos** [comment]
Sorry Mikis Sent from my iPhoneOn 17 Mar 2024, at 15:00, Achim Zeileis ***@***.***> wrote:﻿
I re-applied the previous improvements directly in main now and applied a few further toch-ups. I hope I haven't overlooked anything.

**Comment by zeileis** [comment]
No worries, Mikis, we'll get there!! :wink:

**Pull request closed without merging**
